on: [push]

jobs:
  libraries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0
      - run: zig build --release=fast -Dtarget=x86_64-windows
      - uses: actions/upload-artifact@v4
        with:
          name: x86_64-windows
          path: |
            zig-out/**
            README.md
            LICENSE
